<?xml version="1.0"?>
<!DOCTYPE documentation [ 

<!ELEMENT documentation (logo*,(section)+)>
<!ELEMENT logo (#PCDATA|image)*>
<!ELEMENT image (#PCDATA)>
<!ATTLIST image url CDATA #REQUIRED>
<!ELEMENT section (heading,body)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT body (#PCDATA|paragraph|orderedlist|unorderedlist|image)*>
<!ELEMENT paragraph (#PCDATA|paragraph)*>
<!ATTLIST paragraph style CDATA #IMPLIED>
<!ELEMENT orderedlist (item)+>
<!ELEMENT item (#PCDATA|paragraph|link)*>
<!ELEMENT unorderedlist (item)+>
<!ELEMENT link (displaytext, url)>
<!ELEMENT displaytext (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ENTITY trademark "$#174;">
]>
<documentation>
	<logo>
	Apache Kafka - A distributed streaming platform
	
		<image url="https://kafka.apache.org/images/logo.png"></image>
	</logo>
	<section>
		<heading>Introduction</heading>
		<body>
			<paragraph style="bold">
			Apache Kafka&trademark; is
			
				<paragraph style="italics">a distributed streaming platform.</paragraph>
			What exactly does that mean?
		
			</paragraph>
			<paragraph>We think of a streaming platform as having three key capabilities:</paragraph>
			<orderedlist>
				<item>It lets you publish and subscribe to streams of records. In this respect it is similar to a message queue or enterprise messaging system.</item>
				<item>It lets you store streams of records in a fault-tolerant way.</item>
				<item>It lets you process streams of records as they occur.</item>
			</orderedlist>
			<paragraph>What is Kafka good for?</paragraph>
			<paragraph>It gets used for two broad classes of application:</paragraph>
			<orderedlist>
				<item>Building real-time streaming data pipelines that reliably get data between systems or applications</item>
				<item>Building real-time streaming applications that transform or react to the streams of data</item>
			</orderedlist>
			<paragraph>To understand how Kafka does these things, let's dive in and explore Kafka's capabilities from the bottom up.</paragraph>
			<paragraph>First a few concepts:</paragraph>
			<unorderedlist>
				<item>Kafka is run as a cluster on one or more servers.</item>
				<item>The Kafka cluster stores streams of 
					<paragraph style="italics">records</paragraph> 
					in categories called 
					<paragraph style="italics">topics.</paragraph>
				</item>
				<item>Each record consists of a key, a value, and a timestamp.</item>
			</unorderedlist>
			<image url="https://kafka.apache.org/0110/images/kafka-apis.png"></image>
			<paragraph>Kafka has four core APIs:</paragraph>
			<unorderedlist>
				<item>
					The 
					<link>
						<displaytext>Producer API</displaytext>
						<url>https://kafka.apache.org/documentation.html#producerapi</url>
					</link> 
					allows an application to publish a stream of records to one or more Kafka topics.
				</item>
				<item>
					The 
					<link>
						<displaytext>Consumer API</displaytext>
						<url>https://kafka.apache.org/documentation.html#consumerapi</url>
					</link> 
					allows an application to subscribe to one or more topics and process the stream of records produced to them.
				</item>
			</unorderedlist>
		</body>
	</section>
</documentation> 